### PR TITLE
Adds ability to save past searches

### PR DESCRIPTION
**Pull request by ModoUnreal**
So the title says it all. You can get an idea of what I'm going for with this pull request. A few things to note: The "history.txt" file is automatically put in the storage folder, it just seems like the most appropriate way of going about the storage of it.
Also I still haven't changed the numbers in the setup.py file, so the (4/29) stuff that appears when configuring Pyweather.
So I'll clean it up a bit either today or tomorrow, so test it out if you want to see how it works.

Oh yeah and kudos to the "achievements" stuff you put I find that really cool, I will probably add something like that to PyElement (my project) once I get it properly started.

### CODE REVIEW

**Comment by o355** [comment]
Thanks for correcting that typo on the geocoder config :)

Also, what exactly do you mean by achievements? I can't recall what stuff I put in my program. Only thing I can think about is the contributor ranks.

**Comment by ModoUnreal** [comment]
That's what I meant, the contributor ranks stuff! I don't know, I just find these sorts of things cool. I'm the sort of guy that tries to get all achievements on videogames or 100% an exam................................... Doesn't mean I succeed though, ha!
Oh yeah, and you're welcome, it was bugging me that's all!

**Comment by o355** [comment]
This feature does look interesting. However, I have a few recommendations.

1. How will this get incorporated into PyWeather? Will a user type in `prevloc:1` and so on and so forth into `locinput` to call their previous searches?
2. If location history is just limited to a text file, I can't see the value of having this. 
3. Do you plan to have any way to read back location history, or at least limit the entries in the text file? I feel as if over months of this on, a large text file would get created.
4. I'd highly suggest using the config file to store historical data. This is at least what I would do to store the data.

Make a LOCATIONHISTORY section regardless if the user has loc history enabled or disabled, with 5 entries of loc1, loc2, up to loc5 with "None" as the value of each. 

When PyWeather is launched, display the available locations to a user, as such:
```
You can also enter in shortcuts for weather data for a location/PWS.

Previous locations:
prevloc:1 - Location 1
prevloc:2 - Location 2
```

And so on and so forth. When a user enters a new location, bump all cities down. Basically...
Location 1 = 2
2 = 3
3 = 4
4 = 5
And write the new location for 1 into the config file.

It's up to you if you want to take my comments into consideration. I could see having direct PyWeather integration as being benefital, and won't conflict with favorite locations (please let me code this in thanks :) ) when I add it.

**Comment by ModoUnreal** [comment]
I was thinking of doing something like you mentioned, of course the code I added right now is very rough and is just there to showcase how it roughly functions. I'll try and improve it tomorrow and will definitely consider your recommendations, they are definitely what I kind of had in mind. 
Apologies for the wait, I did just code all this in on impulse!

**Comment by o355** [comment]
Alright. Just a quick note, it'd be greatly appreciated if you post your PR when you're done with your code, so a yesterday's weather isn't repeated again.

I'm going to close this PR for now, and you can make another PR when you're done.

**Comment by ModoUnreal** [comment]
Sure thing!

**Pull request closed without merging**
