### PR TITLE
Previous locations

### PR DESCRIPTION
**Pull request by ModoUnreal**
So as the title suggests, this is the code for previous locations, so it can be configured on the setup.py script and can also be displayed in it's own menu. Can also remove any previous locations.

By all means please test it out, as per usual and feedback!

### CODE REVIEW

**Comment by o355** [comment]
Awesome! Thanks for the PR. I'll test this on Friday as I'm busy until then.

**Comment by o355** [comment]
Thanks for the PR, I'm still messing around with your code but I've got a few comments already.

Since airports is now a thing, you'll want to make sure you add prevloc1_data (and so on and so forth) to show the properly formatted airport name. You can get the airport name with the variable `airport_name`.

In addition, I looked at your code and you're attempting to get a boolean when loading the config variables, make sure you're just doing `config.get()`.

In addition, when I looked up an airport location, prevloc1 was set to NoneAirport, but nothing was committed into the config file (it stayed None in the config file). Also for some other weird reason I can't query the geocoder on your copy of PyWeather.

Feel free to do more testing to get the bugs sorted out. I'll leave this PR up as merge conflicts shouldn't occur.

**Comment by ModoUnreal** [comment]
Ok I think I'm done now. Please verify if anything is wrong, especially with airports and pws stuff, mostly because that's where errors are more like to be!

**Comment by o355** [comment]
Alright, I'll do some testing either today or tomorrow.

**Comment by o355** [comment]
Maybe I'll do testing today (or tomorrow). Sorry for the delay. I completely forgot.

Along with your code, I'm planning on adding new query prefixes, see the issue about the prefixes and if you want to add support for those query types.

**Comment by o355** [comment]
I still believe that there is a lot of work to do in making this PR-ready, so I'll list what I've found so far that needs fixing:

(it's a very long list)
* How are you dealing with duplicate previous location inputs? It'd be annoying if a user saw a city 5x for a previous location. In my opinion if there's a duplicate twice (up to 5x) in a row, combine it into one entry. If there's an entry for a city down the list but the user enters it again, delete that entry and bring it to the top of the list. Just do a lowercase match.
* I still can't access previous locations at the first input. (prevloc: and previouslocation: both give nothing).
* Your code isn't properly processing prevloc: and previouslocation: inputs, and storing them as previous locations. It shouldn't be.
* Please remove the "Changes saved!" print message when a location is entered. It's unnecessary and confusing.
* Your code is still not properly processing airports. When I enter `arpt:KJFK`, I get `KJFKAirport` as the location input and nothing in the extra data. At this point I'd recommend copying the code used for parsing airports as favorite locations. 
* The same goes for PWSes. When I enter in a PWS ID of `K12345678` (obviously it's not real), I get back `PWSK12345678` as the input, and that's also in the config file as well.
* Make sure you aren't saving currentlocation queries.
* Previous locations aren't shown at the first input.
* Please remove vulgar comments from the code, as it is a breach of the Code of Conduct for PyWeather (other conduct that is considered inappropriate in a professional setting) - This is your first strike.
* Please make sure that you are merging upstream on a daily basis. I saw old and new updater code, and I'm trying to minimize merge conflicts.

I get it, this list is extremely long, but there's a long, long way until your code is ready to merge. I'm going to deny this PR and please resubmit this when you're done. There's a little under 2 months until QA will begin for 0.6.4 beta.

**Comment by o355** [comment]
Sorry if I was harsh in the previous comment. I'm holding PyWeather up to higher standards nowadays, and that generally means not as many corner cuts.

In the future please submit your PRs when they're done and when you've done some testing to make sure they work, it would be greatly appreciated!

**Comment by ModoUnreal** [comment]
I'm working on it now.

**Pull request closed without merging**
