### PR TITLE
Edits in your massive prints

### PR DESCRIPTION
**Pull request by gsilvapt**
Not entirely sure if this speeds up the code or not but it is matter of writting better looking code. You don't need to have many print statements whenever you want it in a new line. You can add the `\n` statement and Python will print it in a new line. Moreover, this also helps avoiding doing things like `print("Something in one paragraph but hey this is getting huge" + "so I break into a new line for code reading purposes.")`. Just keep pressing enter when you feel you reached your limit (usually 80 characters which you didn't follow some times :stuck_out_tongue:) and when you want a new print statement in a new line, just add `\n`.

Instead of opening an issue, just edited most of your statements in the `setup.py` file and only a few in the `pyweather.py`. Those two files seemed to have the majority of the print statements that could benefit from this practice.

This is just a suggestion. If you prefer keep the code your way, it is perfectly fine!

PS: Great tool!

### CODE REVIEW

**Comment by o355** [comment]
Thanks for the PR! I'll be happy to accept your PR, but there's a small issue when launching both pyweather.py/setup.py. Doing a quick test on setup.py results in:

``` File "setup.py", line 20
    print("Couldn't load your config file. Make sure your spelling is correct.
                                                                             ^
SyntaxError: EOL while scanning string literal```

I'll go ahead and do a little research and see where the code might of went wrong.

Oh, and I'm plenty guilty of going over 80 characters. It should be rectified once 1.0 hits.

**Comment by o355** [comment]
Triple quoting the statement looks to be how it works, but I'll keep doing some more testing.

**Comment by gsilvapt** [comment]
Hum, I might have forgotten to arrange any line somewhere. Can you tell me which line is that error from? I can fix it tomorrow.

**Comment by o355** [comment]
Did some basic testing and everything looks great!

Thanks for the PR, and notifying me of improving my code layout! I'll certainly keep this knowledge in mind when I code future programs.

Credits have been added to the changelog, and I'll get the issue fixed for all scripts by 0.5.2 beta.

Thank you for your contributions to PyWeather! 😄

**Comment by gsilvapt** [comment]
No need to thank me. Seemed a pretty interesting project and there is a lot to it that you can learn from it. For instance, I noticed you did not use any object-oriented programming concepts in there. Whenever you reach a stable level and the thing looks as you like, you should go for it and try to do some application of the concept.

Anyway, your idea seemed interesting and a quick look made me notice you had huge print statements you could avoid. Instead of complaining, I did it myself (although not a good job :smile:) If you write a project road map in the wiki or something, maybe I could step in and contribute more often.

Thank you for the credits although I haven't done much. You did a great job!

**Comment by o355** [comment]
Thanks @gsilvapt! I'm still learning with Python, and generally I've substituted OOP with gigantic conditionals, but I've still got some learning to do.

 When it comes to a roadmap, the to-do list is a bare list of what should get implemented. There's still lots to do, and of course I'm always coming up with new ideas, but I'll certainly consider doing a prettier roadmap than the one in the wiki. I made it early on as a checklist of what I have done.

Thanks for the praise (and the contribution)! :)

**Pull request merged**
