### PR TITLE
Added option to setup 3 day/10day hourly cachetimes

### PR DESCRIPTION
**Pull request by ModoUnreal**
So this PR allows the user to change 3 day and 10 day hourly cachetimes, as described above. As of right now I am only changing the settings file, since I am not entirely sure how you want this to work out or how to actually code for the actual caching system.
Apologies for the recent delays, life has been getting in the way currently.
OF course, modify the code as needed and do whatever is necessary to fix it.

### CODE REVIEW

**Comment by o355** [comment]
Just a quick note: I made some setup file modifications, but I haven't pushed it to GitHub. I'll be pushing them soon, and you'll have to update your branch as well.

I'm fine with doing the integration into the main pyweather script, and thanks for the PR.

**Comment by ModoUnreal** [comment]
Just updated my branch, although I had to modify some code so that it fit with my changes as well. It seems to work, oh yeah and I didn't change your eclipse line that you wrote so I guess that's cool too.
Do whatever you need, I'll try and brainstorm a few ideas for Pyweather whilst I wait.

**Comment by o355** [comment]
Sorry I've been slacking off lately. I will get around to approving these changes, I've just been working on other projects.

**Comment by ModoUnreal** [comment]
Oh don't worry about it man! I know how its like, I'm also a student with multiple other projects. Do whatever you want to do first, then deal with my PR (if you want of course!)

**Comment by o355** [comment]
Code looks good. I'll merge the PR, and I'll do these things myself:
- Properly configuring the cache system for 3 day/10 day in PyWeather. I didn't see much in the way of configuring it, but I can do that myself.
- I'll add the default variables to configupdate, and configsetup.
- I'll find some other things to correct.

Thanks for the PR, and I'll add credit in as always.

**Pull request merged**
